SELECT * FROM flyway_schema_history;
SELECT * FROM TB_DOCTORS;
DELETE FROM TB_DOCTORS;
UPDATE TB_DOCTORS SET ACTIVE = 1;

CREATE TABLE TB_TESTE (NAME VARCHAR(10) NOT NULL, ACTIVE TINYINT);
INSERT INTO TB_TESTE VALUES ('X', 1);
INSERT INTO TB_TESTE VALUES ('Y', NULL);
SELECT * FROM TB_TESTE;
UPDATE TB_TESTE SET ACTIVE = 1 WHERE ACTIVE IS NULL;
ALTER TABLE TB_TESTE MODIFY ACTIVE TINYINT NOT NULL;
DROP TABLE TB_TESTE;