SELECT * FROM FLYWAY_SCHEMA_HISTORY;
SELECT * FROM TB_DOCTORS;
SELECT * FROM TB_PATIENTS;
SELECT * FROM TB_USERS;
SELECT * FROM TB_APPOINTMENTS;

SELECT
	A.ID,
    P.NAME,
    D.NAME,
    DATE_FORMAT(A.APPOINTMENT_TIME, '%d/%m/%Y %Hh') AS APPOINTMENT_TIME
FROM
	TB_APPOINTMENTS A,
    TB_PATIENTS P,
    TB_DOCTORS D
WHERE
	A.PATIENT_ID = P.ID
    AND A.DOCTOR_ID = D.ID
ORDER BY
	A.ID
;

SELECT D.* FROM TB_DOCTORS D WHERE ACTIVE = 1 AND D.ID NOT IN (SELECT A.DOCTOR_ID FROM TB_APPOINTMENTS A WHERE A.APPOINTMENT_TIME = STR_TO_DATE('24/05/2023 18', '%d/%m/%Y %H'));


DROP TABLE TB_APPOINTMENTS;

DELETE FROM FLYWAY_SCHEMA_HISTORY WHERE VERSION = 6;
DELETE FROM TB_APPOINTMENTS;

INSERT INTO TB_APPOINTMENTS VALUES (NULL, 1, 1, NOW());