CREATE TABLE TB_DOCTORS (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    CRM VARCHAR(255),
    EXPERTISE VARCHAR(255),
    STREET VARCHAR(255),
	NEIGHBORHOOD VARCHAR(255),
	ZIP_CODE VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	NUMBER VARCHAR(255),
	COMPLEMENT VARCHAR(255)
);
# DROP TABLE TB_DOCTORS;