CREATE TABLE TB_APPOINTMENTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PATIENT_ID BIGINT NOT NULL,
    DOCTOR_ID BIGINT NOT NULL,
    APPOINTMENT_TIME DATETIME NOT NULL,
    CONSTRAINT FK_APPOINTMENTS_PATIENT_ID FOREIGN KEY (PATIENT_ID) REFERENCES TB_PATIENTS(ID),
    CONSTRAINT FK_APPOINTMENTS_DOCTOR_ID FOREIGN KEY (DOCTOR_ID) REFERENCES TB_DOCTORS(ID)
);