ALTER TABLE TB_APPOINTMENTS ADD COLUMN ACTIVE TINYINT;
ALTER TABLE TB_APPOINTMENTS ADD COLUMN REASON_FOR_CANCELLATION VARCHAR(20);
UPDATE TB_APPOINTMENTS SET ACTIVE = 1;
ALTER TABLE TB_APPOINTMENTS MODIFY ACTIVE TINYINT NOT NULL;